version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: sahana_task_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin234
      POSTGRES_DB: hr_task_management
    ports:
      - "5456:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./Backend
    container_name: sahana_task_backend
    ports:
      - "3100:3100"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: admin234
      DB_NAME: hr_task_management
      DB_PORT: 5432

  frontend:
    build: ./Frontend
    container_name: sahana_task_frontend
    ports:
      - "7013:80"
    depends_on:
      - backend

  hr:
    build: ./HR
    container_name: sahana_task_hr
    ports:
      - "7014:80"
    depends_on:
      - backend

volumes:
  pgdata:

